name: 3DS CI

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  devkitpro/devkitarm:latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Project
      run:  make